[package]
name = "modern-npu-thesis"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["OrangeX4", "yjy"]
license = "MIT"
description = "西北工业大学学位论文模板。Modern Northwestern Polytechnical University Thesis."
repository = "https://github.com/npu-lug/modern-npu-thesis"
keywords = ["Northwestern Polytechnical University", "NPU", "thesis"]
categories = ["thesis"]
exclude = ["imgs"]
compiler = "0.14.2"

[template]
path = "template"
entrypoint = "thesis.typ"
thumbnail = "thumbnail.png"